require "bundler/gem_tasks"
# require "rake/testtask"
require "rspec/core/rake_task"

# Rake::TestTask.new do |t|
#   t.lib << "test"
#   t.test_files = FileList["test/**/*_test.rb"]
#   t.verbose = true
  
# end

RSpec::Core::RakeTask.new(:spec)

task :default => :spec
